type = "about"
title = "About"

[profile]
research_interests = [
  "Robot Learning",
  "World Modeling",
  "Generative Model"
]

[[sections]]
id = "about"
type = "markdown"
source = "bio.md"
title = "About"

[[sections]]
id = "news"
type = "list"
title = "News"
source = "news.toml"


# [[sections]]
# id = "featured_publications"
# type = "publications"
# title = "Selected Publications"
# filter = "selected"
# limit = 5


[[sections]]
id = "misc"
type = "misc"
title = "Misc"
source = "misc.toml"



