type = "card"
title = "Awards"
description = ""

[[items]]
title = "Alishan Scholarship"
subtitle = "Nanjing University"
date = "2025-06"
content = "Top 1% of the students."

[[items]]
title = "Duxia Scholarship"
subtitle = "Nanjing University"
date = "2024-09"
content = "Top 5% of the students."


