[[misc]]
content = "I am a fan of [EVA](https://en.wikipedia.org/wiki/Neon_Genesis_Evangelion). Wish we could build our EVANGELION-01 someday🤩"

[[misc]]
content = "I love reading, watching films, and exploring the lives of people across different cultures and eras around the world. My favourite director is [Edward Yang](https://en.wikipedia.org/wiki/Edward_Yang)"
