[[news]]
date = "2025-09"
content = "AC-DiT was accepted by NeurIPS 2025 🎉"

[[news]]
date = "2025-06"
content = "I received the Alishan Scholarship of Nanjing University"

[[news]]
date = "2024-09"
content = "I was awarded the Duxia Scholarship of Nanjing University"



